### ISSUE TITLE
Installation stuck on step 3: "For some reason, I could not create the feed tracking database."

### ISSUE THREAD

**Issue by DougJoseph** [timwasson/PHP-Podcast-Creator#4]
The code was able to create a table in the MySQL database, titled "feed" ... I can see that by watching the new empty database I created just for this. However, I get the following in the installation wizard:

> Welcome!
> You're moments away from publishing your own podcast. Just finish the steps below.
> For some reason, I could not create the feed tracking database.

Any idea what the issue could be?

**Comment by DougJoseph** [comment]
I could not get the setup wizard to complete, so I manually edited the config.php file. 

I can now get logged into the admin dashboard.

However, my install is not showing much sign of life. If I go to use the admin dashboard for anything I get 500 server errors. I also get 500 server error when I try to visit the public side of the podcast.

One error I saw in the error log on my hosting account is this:

`[22-Dec-2020 08:33:42 UTC] PHP Fatal error:  'break' not in the 'loop' or 'switch' context in / [--my path removed from here for posting--] /components/getid3/getid3.lib.php on line 285`

I have not touched anything related to getid3.

Any ideas?

**Comment by DougJoseph** [comment]
Also, I'm getting unbelievably enormous error logs by only trying to access a page or two, once or twice. I'm talking half a GB for one or two page loads, and a whole GB of error log for maybe three or four page load attempts. I've never seen anything like it. ???

**Comment by DougJoseph** [comment]
I finally moved the media folder into the same folder as the script files, and I'm getting some functionality in the Admin area, but whenever I click the "Change your podcast details" menu option and then (after the page loads) hit save, I get a 500 error, and this pops up in the error log:

`[22-Dec-2020 09:30:02 UTC] PHP Fatal error:  Uncaught Error: **Call to undefined function ereg()** in [my path removed for posting] /core/functions.php:52
Stack trace:
#0 [my path removed for posting] /core/admin/podcastdetails.php(104): validate_email('pastor@cac.us.c...')
#1 [my path removed for posting] /core/admin/admin.php(87): include('/home2/cacliven...')
#2 [my path removed for posting] /index.php(32): include('/home2/cacliven...')
#3 {main}
  thrown in [my path removed for posting] /core/functions.php on line 52`

**Comment by DougJoseph** [comment]
Re. undefined function ereg():

From https://www.php.net/manual/en/function.ereg.php

> Warning
> This function was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0.

> Alternatives to this function include:

> preg_match()

**Comment by DougJoseph** [comment]
SUCCESS on the above by editing /core/functions.php ...
...and replacing "ereg(" with "preg_match("
... at least in so much as the page will now accept a "save" action. Here's the revised version of the given function:

	function validate_email ($address) { //validate email address

	//	return (ereg('^[-!#$%&\'*+\\./0-9=?A-Z^_`a-z{|}~]+'.

	return (preg_match('^[-!#$%&\'*+\\./0-9=?A-Z^_`a-z{|}~]+'. 
	'@'.
		'[-!#$%&\'*+\\/0-9=?A-Z^_`a-z{|}~]+\.'.
	'[-!#$%&\'*+\\./0-9=?A-Z^_`a-z{|}~]+$',
	$address));
	}

**Comment by DougJoseph** [comment]
The PHP-Podcast-Creator code seems to have some major issues with paths. For the config.php file, the Admin dashboard needs "media" and "images" paths that are relative to the script. Yet for the public side to display the MP3 files and images, it expects them to be at paths that are relative to the root of the site. **Those two paths are not always going to be the same!**  Basically, the code seems to assume that the script will always be in the root of the site. In my install, that's not the case.
